### ISSUE TITLE
Make newer version available in this repo

### ISSUE THREAD

**Issue by lisuml** [eu07/maszyna#48]
Current master branch builds version of MaSzyna from August 2019. Is it possible to refresh it so we can have something closer to current stable version (20.01)?

**Comment by lisuml** [comment]
Actually, I can see plenty of dev forks of the repo and seeing https://github.com/tmj-fstate/maszyna is the most recent ones, I tried to build that one, but it's not working with standard cmake approach. Any hint where I can find source code of most recent stable version or above, so I can compile e07 binary natively on Linux?

**Comment by carmel4a** [comment]
Sorry for delay, done. AFAIK repo wasn't maintained because releases were created from @Milek7 fork. Hopefully this repo will become main staging repository in the future.
