### ISSUE TITLE
[Linux] coredump on some scenarios related to Python's thread

### ISSUE THREAD

**Issue by marcinn** [eu07/maszyna#49]
Hi.

I'm using linux native build and I'm getting core dumps. It is 100% reproducible on zwierzyniec_transport.scn. The command line is:

`./eu07 -s zwierzyniec_transport.scn -v ST45-03`

Stack trace:
```
                Stack trace of thread 1447717:
                #0  0x00007f92ad70ece5 raise (libc.so.6 + 0x3bce5)
                #1  0x00007f92ad6f8857 abort (libc.so.6 + 0x25857)
                #2  0x00007f92adee454c Py_FatalError (libpython2.7.so.1.0 + 0x4954c)
                #3  0x00007f92adef0572 PyEval_RestoreThread.cold (libpython2.7.so.1.0 + 0x55572)
                #4  0x000056376b516582 n/a (/home/marcin/.wine/drive_c/Program Files (x86)/MaSzyna/eu07 + 0x1e7582)
                #5  0x0000000000000024 n/a (n/a + 0x0)
```

Backtrace from gdb:

```
Core was generated by `./eu07 -s zwierzyniec_transport.scn -v ST45-03'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f92ad70ece5 in raise () from /usr/lib/libc.so.6
[Current thread is 1 (Thread 0x7f92aceeb780 (LWP 1447717))]
(gdb) bt
#0  0x00007f92ad70ece5 in raise () from /usr/lib/libc.so.6
#1  0x00007f92ad6f8857 in abort () from /usr/lib/libc.so.6
#2  0x00007f92adee454c in Py_FatalError () from /usr/lib/libpython2.7.so.1.0
#3  0x00007f92adef0572 in PyEval_RestoreThread.cold () from /usr/lib/libpython2.7.so.1.0
#4  0x000056376b516582 in python_taskqueue::fetch_renderer(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) ()
#5  0x000056376b516b13 in python_taskqueue::insert(python_taskqueue::task_request const&) ()
#6  0x000056376b569347 in eu07_application::request(python_taskqueue::task_request const&) ()
#7  0x000056376b41a07e in TTrain::Update(double) ()
#8  0x000056376b572c36 in driver_mode::update() ()
#9  0x000056376b569262 in eu07_application::run() ()
#10 0x000056376b3c6e9d in main ()
```

SHA256 of `eu07` executable: `7babdfd9c2a1a5218584eae8ece5c868a1b23bf948b30746eeb6f8f7aae90fb4`

**Comment by Milek7** [comment]
Which MaSzyna you have?

**Comment by marcinn** [comment]
Heh..  AFAIR I downloaded 20.01 from eu07.pl website, then somehow I got Windows installer and installed Maszyna using Wine, and finally I compiled native binary from this repo ( commit c45081b2ebe6b69365742c6b9eb2dc0ab68785be).

**Comment by Milek7** [comment]
Sorry for bit messy state of these repos, newest version that you can compile natively on linux is there: https://github.com/Milek7/maszyna/tree/sim
Sadly it doesn't support 20.01 yet, so if you want use native build use 19.08 pack
(more info here https://eu07.pl/forum/index.php/topic,32403.msg524852.html

**Comment by marcinn** [comment]
Ok, thanks for a quick reply. I'll check your fork!

**Comment by marcinn** [comment]
There is same error for your build (release: M7 15.09.2019) with 19.08 data files :(

**Comment by Milek7** [comment]
Curious, I will check it tommorow.

**Comment by marcinn** [comment]
In version 21.04 the issue is no longer present. Thanks.
